spring:
  data:
    mongodb:
      database: ujjaindb
      host: mongo-shard-00-01-nu04n.mongodb.net
      port: 27017
      username: mongo
      password: mongo
      autoConnectRetry: true
      socketKeepAlive: true
      socketTimeout: 1500